export {default as GeneraPage} from './Header'
export {default as ErrorPage} from './ErrorPage'
export {default as HelpPage} from './HelpPage'
export {default as MainPage} from './MainPage'
export {default as LoginPage} from './LoginPage'
